server:
  port: 9091
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:Pa55w0rd}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:todo_db}
  jpa:
    hibernate:
      ddl-auto: ${DDL_CONFIG:none}
    show-sql: ${SHOW_SQL:true}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  graphql:
    path: /graphql
    graphiql:
      enabled: true
