version: '3.8'

services:
  db:
    image: postgres:13
    container_name: todo_db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Pa55w0rd
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
